### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by LunarDevelopment** [krico/angular-gitkit#5]
Hello! 

I stumbled across your repo as I'm working on a google app engine / gitkit / angularjs project, yours is the only angular-gitkit module I can find but I was wondering if you could let me know if it still works? 

I see it was last updated 9 months ago. 

Also the google app engine requires a session ID token for it's api calls, can I get this from the callback of this log in module if I implement it? 

Thanks for your time in advance!

**Comment by krico** [comment]
Hi @LunarDevelopment, 

I was in the same situation as you when I started this project.  I got side-tracked by moving from Switzerland to USA and by working on [endpoint-angular-client-generator[(https://github.com/krico/endpoints-angular-client-generator).  So in short, not it doesn't work.

I plan to get back to this project in the next few weeks but can't promise you anything.

Regarding the sessionID token, this is something you need to handle yourself, independent of GitKit.  What GitKit gives you is a callback that you can use to perform the user's login.

**Comment by LunarDevelopment** [comment]
That's good to know, Thankyou for taking the time to come back to me.

Have you had any experience with satellizer?  My new idea is to
authenticate a user with that (hopefully that gets me a session I'D too)?
